Fix compilation error caused by default value for template template parameter
g++-5.2 was accepting commit 0be775cce977ef7143d3c96958d152b12618a481
while g++-4.8 and clang-3.9 threw errors
causing issue in the mentioned commit (simulation_object_util.h:167):
template <typename TTBackend=Backend,
          template <typename, typename, int> class TTMemberSelector =
             Base::template MemberSelector>
...